Dar de alta a un usuario #1
BorjaJG/ed-digital-library pull request #2
Opened 2024-04-14 18:43 UTC by BorjaJG

## 📝 Breve descripción del ticket asociado a esta PR

## 👩‍💻 Resumen de los cambios introducidos

## 👁️ Partes del código debe ser revisado con más atención

## 📸 Screenshot o Video

## ✅ Checklist
- [ ] He añadido un título a la PR descriptivo.
- [ ] Me he asignado como autor.
- [ ] El proyecto compila y se ejecuta correctamente.
- [ ] El código se ha probado con todas las opciones posibles.
- [ ] El código ha sido formateado.
- [ ] He eliminado código de prueba.
- [ ] Se han añadido test unitarios.

## ✋ Notas adicionales (Disclaimer)

## 🌈 Añade un Gif que represente a esta PR

2024-04-18 12:54 UTC, AlejandrodePablo commented on src/main/java/com/iesam/digitallibrary/user/domain/User.java
Te recomiendo que si declaras los atributos como _public final_ puedes prescindir de los _getters_ y _setters_, para ahorrar bastante código y porque acostumbramos a hacerlo así en clase.

2024-04-18 13:12 UTC, AlejandrodePablo requested changes
Revisa los comentarios 👍

2024-04-18 13:12 UTC, AlejandrodePablo commented on src/main/java/com/iesam/digitallibrary/user/data/local/UserMemLocalDataSource.java
Yo añadiría un patrón Singleton en esta clase y haría uso de ella, para instanciar la clase cada vez que creemos un usuario.

2024-04-18 13:12 UTC, AlejandrodePablo commented on src/main/java/com/iesam/digitallibrary/user/presentation/UserPresentation.java
> +        NewUserUseCase newUserUseCase = new NewUserUseCase(new UserDataRepository());
Aquí llamaría a la instancia de la clase con el patrón Singleton mencionado en la clase _UserMemLocalDataSource_

2024-04-18 13:12 UTC, AlejandrodePablo commented on src/main/java/com/iesam/digitallibrary/Main.java
Yo crearía el Usuario fuera del _main_, ya sea simplemente crearlo o añadiéndolo a un método

2024-04-18 13:12 UTC, AlejandrodePablo commented on src/test/java/com/iesam/digitallibrary/user/newUser/domain/SaveUserUseCaseTest.java
Añadiría un nuevo test a probar para saber si cada uno de los atributos de un usuario es nulo

2024-04-18 13:35 UTC, BorjaJG commented on src/main/java/com/iesam/digitallibrary/user/data/local/UserMemLocalDataSource.java
Hola, ya lo he implementado en la siguiente funcionalidad de usuario que es obtener un usuario.

2024-04-18 13:38 UTC, BorjaJG commented on src/main/java/com/iesam/digitallibrary/Main.java
También lo implementado en la otra PR.

2024-04-18 13:39 UTC, BorjaJG commented on src/test/java/com/iesam/digitallibrary/user/newUser/domain/SaveUserUseCaseTest.java
Te refieres a cada uno de los valores  o al conjunto.

2024-04-18 14:33 UTC, BorjaJG commented
Y he realizado los cambios que me pediste. Para que lo revises.

2024-04-22 18:09 UTC, AlejandrodePablo commented on src/main/java/com/iesam/digitallibrary/user/data/local/UserMemLocalDataSource.java
Perfecto, acuérdate de usarlo cuando sea necesario 👍

2024-04-22 18:38 UTC, AlejandrodePablo commented on src/test/java/com/iesam/digitallibrary/user/newUser/domain/SaveUserUseCaseTest.java
Así está bien

2024-04-23 16:36 UTC, AlejandrodePablo approved these changes
Todo correcto 👍

2024-04-24 15:21 UTC, merged